language: node_js
sudo: true
node_js: stable
script:
- npm test
env:
  global:
  - CF_APP=document-conversion-demo
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=demos
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    repo: watson-developer-cloud/document-conversion-nodejs
    branch: master
  skip_cleanup: true
